language: java

jdk:
  - oraclejdk8

matrix:
  fast_finish: true

install: "rake special:bootstrap"

script: "mvn clean install"

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18c65e29b9926a658da8
    on_success: always
    on_failure: always
    on_start: true
