language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk7
    - jdk: openjdk7

install: "rake special:bootstrap"

script: "mvn clean install"

notifications:
  irc: "irc.freenode.org#golo-lang"
