language: java

# oraclejdk7 is broken in 1.7.0_45-b18
jdk:
  - openjdk7
  - oraclejdk8

install: "rake special:bootstrap"

script: "mvn clean install"

notifications:
  irc: "irc.freenode.org#golo-lang"
